/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Fachada.HorarioRestauranteFCD;
import DTOs.RestauranteDTO;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebastian Murrieta Verduzco - 233463
 */
public class Ajustes extends javax.swing.JFrame {

    /**
     * Creates new form Ajustes
     */
    public Ajustes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        establecerHorarioBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        horaCierreTimePicker = new raven.datetime.component.time.TimePicker();
        horaInicioTimePicker = new raven.datetime.component.time.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Horario restaurante");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        regresarBtn.setBackground(new java.awt.Color(102, 102, 102));
        regresarBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        regresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 150, 50));

        establecerHorarioBtn.setBackground(new java.awt.Color(102, 102, 102));
        establecerHorarioBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        establecerHorarioBtn.setForeground(new java.awt.Color(255, 255, 255));
        establecerHorarioBtn.setText("Establecer");
        establecerHorarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                establecerHorarioBtnActionPerformed(evt);
            }
        });
        getContentPane().add(establecerHorarioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 150, 50));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Horario de apertura");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Horario de cierre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 200, -1, -1));

        jPanel1.setBackground(new java.awt.Color(22, 22, 22));

        horaCierreTimePicker.setBackground(new java.awt.Color(28, 28, 28));
        horaCierreTimePicker.setForeground(new java.awt.Color(255, 255, 255));
        horaCierreTimePicker.setColor(java.awt.Color.darkGray);
        horaCierreTimePicker.setFocusCycleRoot(true);

        horaInicioTimePicker.setBackground(new java.awt.Color(28, 28, 28));
        horaInicioTimePicker.setForeground(new java.awt.Color(255, 255, 255));
        horaInicioTimePicker.setColor(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(horaInicioTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 541, Short.MAX_VALUE)
                .addComponent(horaCierreTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horaInicioTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaCierreTimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        new Admistrador().setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void establecerHorarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_establecerHorarioBtnActionPerformed
        try {
            LocalTime apertura = horaInicioTimePicker.getSelectedTime();
            LocalTime cierre = horaCierreTimePicker.getSelectedTime();

            if (apertura == null || cierre == null) {
                throw new IllegalArgumentException("Debe seleccionar ambas horas.");
            }

            // Convertir LocalTime a String con formato
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
            String aperturaStr = apertura.format(formatter);
            String cierreStr = cierre.format(formatter);

            RestauranteDTO restaurante = new RestauranteDTO();
            HorarioRestauranteFCD fachadaHorario = new HorarioRestauranteFCD();

            // Establecer horas en la fachada
            fachadaHorario.establecerHoraApertura(restaurante, aperturaStr);
            fachadaHorario.establecerHoraCierre(restaurante, cierreStr);

            JOptionPane.showMessageDialog(this, "Horario actualizado exitosamente.\n"
                    + "Apertura: " + aperturaStr + "\nCierre: " + cierreStr,
                    "Confirmación", JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al establecer el horario.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_establecerHorarioBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton establecerHorarioBtn;
    private raven.datetime.component.time.TimePicker horaCierreTimePicker;
    private raven.datetime.component.time.TimePicker horaInicioTimePicker;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
